project:
  type: website

# website:
#   title: "website"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: q1_variable.qmd
  #       text: Variables

  #   right:
  #     - text: "More"
  #       menu:
  #         - about.qmd

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics"
        contents:
          - text: "Variables"
            href: q1_variable.qmd


            



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



